// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Prisma 7では、directUrlは環境変数から自動的に読み込まれます
    // DATABASE_URL_UNPOOLED または POSTGRES_URL_NON_POOLING を設定してください
  },
});
