// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/**
 * Prisma設定ファイル
 *
 * 環境変数の設定:
 * - DATABASE_URL: PostgreSQL接続文字列（アプリケーション用・マイグレーション用）
 * - DATABASE_URL_UNPOOLED: プールされていない接続（マイグレーション用、オプション）
 */
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // データベース接続文字列
    // DATABASE_URL_UNPOOLED が設定されている場合は優先的に使用（マイグレーション用）
    url: process.env["DATABASE_URL_UNPOOLED"] || process.env["DATABASE_URL"],
    // directUrlは自動的にurlと同じ値が使用されます
  },
});
