// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/**
 * Prisma設定ファイル
 *
 * マイグレーション実行時は、通常のデータベース接続文字列が必要です。
 * Prisma Accelerateはマイグレーションには使用できません。
 *
 * 環境変数の設定:
 * - DATABASE_URL: Prisma AccelerateのURL（アプリケーション用）
 * - POSTGRES_URL または DATABASE_URL_UNPOOLED: 通常のデータベース接続文字列（マイグレーション用）
 */
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // マイグレーション用の接続文字列（通常のPostgreSQL接続）
    // POSTGRES_URL または DATABASE_URL_UNPOOLED を優先的に使用
    url: process.env["POSTGRES_URL"] || process.env["DATABASE_URL_UNPOOLED"] || process.env["DATABASE_URL"],
    // directUrlは自動的にurlと同じ値が使用されます
  },
});
