/**
 * アプリケーション全体の設定を一元管理
 */

export const config = {
  imageConfig: {
    // Vercelの関数ペイロードサイズ制限（約4.5MB）に合わせて4MBに設定
    MAX_FILE_SIZE_MB: 4,
    MAX_FILE_SIZE_BYTES: 4 * 1024 * 1024,
    COMPRESSION_TARGET_SIZE_MB: 3.5,
    MAX_IMAGE_WIDTH: 1920,
    MAX_IMAGE_HEIGHT: 1920,
    COMPRESSION_QUALITY: 0.85,
    MAX_INPUT_SIZE_MB: 50,
    MAX_INPUT_SIZE_BYTES: 50 * 1024 * 1024,
    RECOMMENDED_FILE_SIZE_MB: 10,
    IMAGE_LOAD_TIMEOUT_MS: 60000,
    CREATE_IMAGE_BITMAP_THRESHOLD_MB: 5,
    CREATE_IMAGE_BITMAP_THRESHOLD_BYTES: 5 * 1024 * 1024,
  },

  blobConfig: {
    PRODUCT_IMAGE_FOLDER: "products",
    CACHE_CONTROL_MAX_AGE: 31536000, // 1年
  },

  apiConfig: {
    PRODUCT_LIST_CACHE_SECONDS: 60,
    PRODUCT_LIST_STALE_WHILE_REVALIDATE_SECONDS: 120,
    CATEGORY_LIST_CACHE_SECONDS: 300,
    CATEGORY_LIST_STALE_WHILE_REVALIDATE_SECONDS: 600,
  },

  displayConfig: {
    GRID_COLUMNS: 3,
    MODAL_CLOSE_DELAY_MS: 300,
  },

  dndConfig: {
    // クリックとドラッグを区別するための最小移動距離
    POINTER_ACTIVATION_DISTANCE: 5,
    // 長押しでドラッグを開始するまでの待機時間
    TOUCH_ACTIVATION_DELAY: 200,
    TOUCH_TOLERANCE: 5,
  },

  animationConfig: {
    STAGGER_CHILDREN_SECONDS: 0.08,
    FADE_IN_DURATION_SECONDS: 0.4,
    SCROLL_ANIMATION_DURATION_SECONDS: 0.5,
  },
} as const;
